dist: focal
language: python
python:
- '3.8'
- '3.9'
- '3.10'
install:
- python3 -m pip install -r requirements.txt
script:
- bash ci/tests/travis-test.sh
- pyinstaller --onefile bin/scout-cli/scout-cli.py
