dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- python3 -m pip install -r requirements.txt
script:
- bash ci/tests/travis-test.sh
- pyinstaller --onefile bin/scout-cli/scout-cli.py
